apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-eapoperator
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: eapoperator-ns
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-eap
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: operator-operator-group
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: eap
                  namespace: openshift-eap
                spec:
                  targetNamespaces:
                    - openshift-eap
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: eap-operator-subscription
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: eap
                  namespace: openshift-eap
                spec:
                  installPlanApproval: Automatic
                  name: eap
                  source: do480-catalog
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: jboss-eap-instance
        spec:
          remediationAction: enforce
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: eap.jboss.org/v1
                kind: WildFlyServer
                metadata:
                  name: jboss-eap-instance
                  namespace: openshift-eap
                spec:
                  applicationImage: "registry.redhat.io/jboss-eap-7/eap73-openjdk11-openshift:latest"
                  replicas: 2
                  env:
                    - name: DB_SERVICE_PREFIX_MAPPING
                      value: "example-db-postgresql=DB"
                    - name: DB_JNDI
                      value: "java:/jboss/datasources/ExampleDS"
                    - name: DB_USERNAME
                      value: "admin"
                    - name: DB_PASSWORD
                      value: "password"
                    - name: DB_DATABASE
                      value: "exampledb"
                    - name: DB_DRIVER
                      value: "postgresql"
                    - name: DB_NONXA
                      value: "true"
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "500m"
                    limits:
                      memory: "1Gi"
                      cpu: "1"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-eapoperator
  namespace: policies
placementRef:
  name: placement-policy-eapoperator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-eapoperator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-eapoperator
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - production
          - development

