apiVersion: operator.open-cluster-management.io/v1
kind: Placement
metadata:
  name: multi-cluster-placement
  namespace: open-cluster-management
spec:
  clusters:
    - name: cluster-1
    - name: cluster-2
