apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: production-clusters
  namespace: policies
spec:
  clusterSelector:
    matchExpressions:
      - {key: env, operator: In, values: ["production"]}
