---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: httpd-placement-rule
  namespace: open-cluster-management
spec:
  clusterSelector:
    matchLabels:
      environment: production
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: httpd-placement-binding
  namespace: open-cluster-management
placementRef:
  kind: PlacementRule
  name: httpd-placement-rule
subjects:
  - kind: Application
    name: httpd
    apiGroup: app.k8s.io
